services:
    secomea:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        container_name: secomea
        ports:
            - 11444:11444
        volumes:
            - ${SNAP_DATA}/docker-volumes/ctrlx-docker-secomea:/etc/sitemanager:rw
        restart: on-failure
