version: "3.7"
services:
    mosquitto:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        container_name: mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ${SNAP_DATA}/docker-compose/docker-mosquitto/config:/mosquitto/config
            - ${SNAP_DATA}/docker-volumes/docker-mosquitto/data:/mosquitto/data
            - ${SNAP_DATA}/docker-volumes/docker-mosquitto/log:/mosquitto/log
        restart: always
