version: "3.7"
services:
    mosquitto:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        container_name: mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ${SNAP_DATA}/docker-compose/ctrlx-docker-mosquitto-ethercat/config:/mosquitto/config
            - ${SNAP_DATA}/docker-volumes/ctrlx-docker-mosquitto-ethercat/data:/mosquitto/data
            - ${SNAP_DATA}/docker-volumes/ctrlx-docker-mosquitto-ethercat/log:/mosquitto/log
        restart: on-failure
    ctrlx-datalayer-mqtt-ethercat:
        image: ${IMAGE_NAME2}:${IMAGE_TAG2}
        container_name: datalayer-mqtt-interface
        restart: on-failure
